### ISSUE TITLE
Add locations to waterbodies drop down

### ISSUE THREAD

**Issue by jakemorr** [bcgov/invasivesBC-mussels-iOS#298]
**As a** *Conservation Officer* **I want** *Snake River, Twin Falls, Idaho & Osoyoos Lake, Oroville, Washington* **So That** *I can use the drop down to fill out the inspection as these are common waterbodies used*

**Additional Context**
-just adding these to the waterbodies list

**Acceptance Criteria**
- [ ] Given I am filling out an inspection, When I go to a waterbodies dropdown, Then Snake River, Twin Falls, Idaho is available for selection
- [ ] Given I am filling out an inspection, When I go to a waterbodies dropdown, Then Osoyoos Lake, Oroville, Washington is available for selection

**Comment by LocalNewsTV** [comment]
From DC:
his might be something we need the Service Owners to verify before adding to what's already there, as there's a bit more information that needs to be precisely given in terms of long/lat and distances. I think we talked to CM about this at the start of the season, so he might have something prepped since then.
 
For example, the CSV looks like this:
 
```csv
water_body_name,water_body_longitude,water_body_latitude,country_code,province_code,closest_city,distance
Andrew Lake,-110.11712,59.88449,CAN,AB,Fort Smith,111
Athabasca,-113.87344,55.4061,CAN,AB,Slave Lake,53.4
Athabasca River,-111.32652,58.52027,CAN,AB,Fort Chipewyan,31.7
```
(and so on)
 
It's from this csv file: https://github.com/bcgov/lucy-web/blob/dev/api/api_sources/resources/csv/WaterBody.csv

**Comment by chrispmad** [comment]
Hello team,

Please find a short .csv file attached that lists the info for those two waterbodies that are to be added.

[manual_addition_wbs_2024_preseason.csv](https://github.com/bcgov/invasivesBC-mussels-iOS/files/14910863/manual_addition_wbs_2024_preseason.csv)
