### ISSUE TITLE
Deploy drain plug text change to App Store

### ISSUE THREAD

**Issue by jakemorr** [bcgov/invasivesBC-mussels-iOS#322]
**Describe the task**
After the text change was deployed to TestFlight we need to get it in to the official version of the app on the app store

**Purpose**
we need to be able to successfully deploy changes to inspect

**Acceptance Criteria**
- [ ] App gets sent to apple for review
- [ ] App gets deployed on app store

**Additional context**
- https://stackoverflow.com/questions/44017769/pushing-from-testflight-to-appstore-new-version
- can take 24 hours for a version to get from the apple review to the app store
- Will need an apple account to connect the developer side of the apple store : Should make an account with BC Govt email

**Comment by PaulGarewal** [comment]
# Progress Update

- App build is now sent to Apple for review (Can take up to 24 hours)

- One hitch was I did not get the last part of the last action to build in workflows. This is due to TestFlight requiring a beta app review, once I placed that review in TestFlight, the current job will only run on another push to master due to how the automatic build number is incremented by run and an offset. (If this is confusing I will elaborate more during stand up).

- This is a non issue, since we did not require extensive testing and will wait for the Apple Review Confirmation.
